region: us
version: '2'
authtoken: 2fV1ALPi1bst6zf8SsFxr39k8dc_7i4NNQuvvumNphJr5RDEt
tunnels:
  twilio-app:
    addr: twilio-app:8001
    proto: http
  plivo-app:
    addr: plivo-app:8002
    proto: http
  bolna-app:
    addr: bolna-app:5001
    proto: http